JWTConfig:
  SecretKey: "SecretKey"
  OperationKey: "OperationKey"

LoggerConfig:
  MaxSize: 200
  MaxBackups: 3
  Level: info

EnablePlayground: true

Debug: true


CORSAllowedOrigins:
  - "*"

PostgresConfig:
  Host: 192.168.31.20
  Port: 5432
  User: root
  Password: root
  DBName: fireworks


CreeperConfig:
  Uri: http://192.168.31.20:8745
  Token: my_token

WarehouseConfig:
  Uri: http://127.0.0.1:8187
  AccessKey: access_key
  SecretKey: secret_key
