JWTConfig:
  SecretKey: "SecretKey"
  OperationKey: "OperationKey"

LoggerConfig:
  MaxSize: 200
  MaxBackups: 3
  Level: info

EnablePlayground: true

Debug: true


CORSAllowedOrigins:
  - "*"

PostgresConfig:
  Host: 192.168.88.99
  Port: 5432
  User: root
  Password: root
  DBName: p_test


CreeperConfig:
  Uri: http://192.168.88.203:8745

WarehouseConfig:
  Uri: http://127.168.88.99:8187
  AccessKey: access_key
  SecretKey: secret_key
